apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent-pod
  namespace: devops-tools
spec:
  initContainers:
    - name: volume-mount-non-root-user
      image: alpine:3.6
      command: ["/bin/bash","-c","chown -R 1001:1001 /root/.m2 && chown -R 1001:1001 /var/run/docker.sock && chmod -R ug+rwx /root/.m2"]
      #command: ["chown", "-R", "1001:1001", "/root/.m2"]
      #command: ["chown", "-R", "1001:1001", "/var/run/docker.sock"]
      volumeMounts:
        - name: m2-home
          mountPath: /root/.m2
        - name: docker-socket
          mountPath: /var/run/docker.sock
  containers:
    - name: jenkins-agent
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
      image: "${env.image_name}"
      volumeMounts:
        - name: m2-home
          mountPath: $HOME/.m2
        - name: docker-socket
          mountPath: /var/run/docker.sock
  volumes:
    - name: m2-home
      hostPath:
        path: $HOME/.m2
        type: DirectoryOrCreate
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
        type: Socket